kind: ReplicationController
apiVersion: v1
metadata:
  name: reviewbook
  labels:
    app: reviewbook
spec:
  replicas: 3
  selector:
    app: reviewbook
  template:
    metadata:
      labels:
        app: reviewbook
    spec:
      containers:
      - name: reviewbook
        image: registry.k8s.io/reviewbook:v3
        ports:
        - name: http-server
          containerPort: 3000
