apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis
    role: replica
spec:
  ports:
    - port: 6379
      targetPort: redis-server
  selector:
    app: redis
    role: replica
